name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: "galamrani/auction-svc"
            path: "src/AuctionService"
          - name: "galamrani/search-svc"
            path: "src/SearchService"
          - name: "galamrani/bid-svc"
            path: "src/BiddingService"
          - name: "galamrani/identity-svc"
            path: "src/IdentityService"
          - name: "galamrani/gateway-svc"
            path: "src/GatewayService"
          - name: "galamrani/notify-svc"
            path: "src/NotificationService"
          - name: "galamrani/web-app"
            path: "client/web-app"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:latest
